// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyTitle("BreathTraitsAffectBreathing")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyProduct("BreathTraitsAffectBreathing")]
[assembly: AssemblyCopyright("Copyright © asquared31415 2020")]

[assembly: AssemblyVersion("0.0.0.0")]
