// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyTitle("MicroTransformer")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyProduct("MicroTransformer")]
[assembly: AssemblyCopyright("Copyright © asquared31415 2020")]

[assembly: AssemblyVersion("2020.3.18.24992")]
